version: '3.8'
services:
  AutomaticServiceCharge:
    build:
      context: ./Banhcafe.Microservices.AutomaticServiceCharge
      dockerfile: src/Api/Dockerfile
    image: AutomaticServiceCharge
    container_name: AutomaticServiceCharge
    environment:
      ASPNETCORE_ENVIRONMENT: development
    ports:
      - "5000:5000"
    network_mode: bridge
